name: fire_detector_app
description: A real-time fire detection app using Flutter and TFLite
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  tflite_flutter: ^0.10.0
  tflite_flutter_helper: ^0.4.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
