name: Detector_app
description: Flutter app para abrir la cámara en iOS y Android.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
   flutter:
    sdk: flutter
  camera: ^0.10.0
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/model.tflite
  - assets/labels.txt
